apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: httpd-gke
  namespace: simple-app
  labels:
    app: httpd
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-4-assets-gke
spec:
  channel:  simple-app/federation
  placement:
    placementRef:
      kind: PlacementRule
      name: cluster-gke
